# Generated by Django 5.2.3 on 2025-06-12 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=200, verbose_name="Nome do Negócio"),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("ecommerce", "E-commerce"),
                            ("services", "Serviços"),
                            ("saas", "SaaS / Software"),
                            ("retail", "Varejo Físico"),
                            ("restaurant", "Restaurante / Food"),
                            ("health", "Saúde / Wellness"),
                            ("education", "Educação"),
                            ("consulting", "Consultoria"),
                            ("other", "Outro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Negócio",
                    ),
                ),
                ("target_audience", models.TextField(verbose_name="Público-Alvo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.CreateModel(
            name="MarketingAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_strategy", models.TextField(verbose_name="Estratégia Atual")),
                ("goals", models.TextField(verbose_name="Objetivos de Marketing")),
                (
                    "analysis_result",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Resultado da Análise"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="agent.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análise de Marketing",
                "verbose_name_plural": "Análises de Marketing",
                "ordering": ["-created_at"],
            },
        ),
    ]
