# Generated by Django 5.2.3 on 2025-11-04 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="annual_revenue",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mei", "MEI (até R$ 81k)"),
                    ("me", "ME (R$ 81k - R$ 360k)"),
                    ("epp", "EPP (R$ 360k - R$ 4.8M)"),
                    ("other", "Outro / Não sei informar"),
                ],
                max_length=8,
                null=True,
                verbose_name="Porte/Faturamento Anual",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="competitive_advantage",
            field=models.TextField(
                blank=True, null=True, verbose_name="Diferencial Competitivo"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="competitors",
            field=models.TextField(
                blank=True, null=True, verbose_name="Principais Concorrentes"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="employees",
            field=models.CharField(
                blank=True,
                choices=[
                    ("solo", "Eu sozinho"),
                    ("1-5", "1-5"),
                    ("6-20", "6-20"),
                    ("20+", "+20"),
                ],
                max_length=8,
                null=True,
                verbose_name="Número de Funcionários",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="main_challenge",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meu Maior Desafio"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="primary_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("increase_sales", "Aumentar minhas vendas"),
                    ("reduce_costs", "Reduzir meus custos"),
                    ("organize_finances", "Organizar minhas finanças"),
                    ("improve_marketing", "Melhorar meu marketing"),
                    ("exploring", "Apenas explorando"),
                ],
                max_length=32,
                null=True,
                verbose_name="Meu Principal Objetivo",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="short_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição Curta"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="years_active",
            field=models.CharField(
                blank=True,
                choices=[("lt1", "< 1 ano"), ("1-3", "1-3 anos"), ("gt3", "+3 anos")],
                max_length=8,
                null=True,
                verbose_name="Tempo de Atividade",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="business_name",
            field=models.CharField(max_length=200, verbose_name="Nome da Empresa"),
        ),
        migrations.AlterField(
            model_name="company",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("ecommerce", "E-commerce"),
                    ("services", "Serviços"),
                    ("saas", "SaaS / Software"),
                    ("retail", "Varejo Físico"),
                    ("restaurant", "Restaurante / Food"),
                    ("health", "Saúde / Wellness"),
                    ("education", "Educação"),
                    ("consulting", "Consultoria"),
                    ("other", "Outro"),
                ],
                max_length=50,
                verbose_name="Setor de Atuação",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="target_audience",
            field=models.TextField(verbose_name="Público-Alvo (ICP)"),
        ),
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo Enviado",
                "verbose_name_plural": "Arquivos Enviados",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
